### PR TITLE
Fix concurrency problem during the classification of instances

### LINKED ISSUE #17: Possible concurrency problem when classifying
While the access to the rConnection is synchronized, thus preventing concurrency problems, we are using a global variable to setup the instance to classify on https://github.com/feedzai/feedzai-openml-r/blob/master/openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java#L111

This means that if 2 threads try to classify in instance, it may happen that thread_1 setups it's instance, and in the meanwhile thread_2 setups other instance, and both threads end classifying the same instance.

the `classify` and `getClassDistribution` method should probably be synchronized.

### PR DESCRIPTION
**Pull request by paulojrp**
Fixes #17 by changing the R functions used to classify instances to receive a new parameter with the instance to be classified. The conversion of an instance to data frame was moved to be called inside the synchronized method used to evaluate the instance.

### CODE REVIEW

File: openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java [hunk 1]
```diff
@@ -148,26 +152,21 @@ public synchronized void close() {
...
-     * Creates a new variable in R with the {@code instance} to classify.
-     *
-     * @param instance The instance to classify.
-     * @throws RserveException If there is an error with the connection to Rserve.
-     * @throws REXPMismatchException If it cannot convert an object to an expected type.
-     */
-    private synchronized void createEvent(final Instance instance) throws RserveException, REXPMismatchException {
+    private synchronized REXP evaluateInstance(final String function,
+                                               final Instance instance) throws RserveException, REXPMismatchException {
         this.rConnection.assign(ProviderRObject.INSTANCE_VARIABLE.getName(), convertInstanceToDataFrame(instance));
```
Comment (pedrorijo91) [inline openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java]: `ProviderRObject.INSTANCE_VARIABLE.getName()` can be refactored into a variable since you are calling it twice no?

File: openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java [hunk 2]
```diff
@@ -148,26 +152,21 @@ public synchronized void close() {
     }
 
     /**
-     * Uses the connection to Rserve to execute a expression. This method needs to be synchronized because the
-     * connection to Rserve isn't thread-safe.
+     * Calls a R {@code function} to evaluate an {@code instance}.
+     * This function depends on the {@link RConnection connection to Rserve} to run R code. The connection to Rserve
+     * isn't thread-safe and so this method needs to be synchronized.
```
Comment (pedrorijo91) [inline openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java]: since we are on this topic: can you add a link on this class javadoc where it says/explains that the rconnection isn't thread safe? 

While it is not a 1st level topic, I think this link referes to this topic: http://rforge.net/Rserve/

> Rserve is thread safe across connections, but eval methods are not thread safe within one connection. This means that multiple threads should not use the same connection unless they guarantee that no eval calls are run in parallel.

**Comment by paulojrp** [comment]
I'm improving the UT to cover this failure (https://github.com/feedzai/feedzai-openml/pull/22).
I will update this branch it that but first I need to bump a new release of openml-utils with that improvement.

**Comment by nmldiegues** [comment]
@paulojrp https://github.com/feedzai/feedzai-openml/pull/22 has been merged; you can release a new hf version and continue working here

File: pom.xml [hunk 3]
```diff
@@ -86,7 +86,7 @@
         <assertj.version>3.7.0</assertj.version>
         <jackson.version>2.6.7</jackson.version>
         <jackson-databind.version>2.6.7</jackson-databind.version>
-        <openml-api.version>0.1.0</openml-api.version>
+        <openml-api.version>0.1.1</openml-api.version>
```
Comment (pedrorijo91) [inline pom.xml]: build failed because this version is still not on maven central. let's wait for some time...

File: openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java (hunk 2 above)
Comment (pedrorijo91) [reply openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java]: ping

File: pom.xml (hunk 3 above)
Comment (pedrorijo91) [reply pom.xml]: build is green

File: openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java (hunk 2 above)
Comment (paulojrp) [reply openml-r-common/src/main/java/com/feedzai/openml/r/ClassificationGenericRModel.java]: I added a link at the end of the javadoc
`@see <a href="http://rforge.net/Rserve/">Rserve</a>`

I searched their source code but the only reference to a thread-safe problem doesn't explain anything.
https://github.com/s-u/Rserve/blob/master/src/include/sbthread.h
> /* this isn't really thread-safe, but creating more mutexes
     at exactly the same time by different threads on an SMP machine
     is ... let's say inprobable. moreover ++ might be atomic.
     creating yet another mutex for this single operation seems
     to me as an overkill. but if you need 100% thread-safe code,
     feel free to implement it here ;) */

I prefer the description presented on their website (http://rforge.net/Rserve/)
> Rserve is thread safe across connections, but eval methods are not thread safe within one connection. This means that multiple threads should not use the same connection unless they guarantee that no eval calls are run in parallel.

**Comment by nmldiegues** [comment]
LGTM

this should not be back-ported to hf-0.1.X, but rather a hf-0.2.X should be branched off, as it is a breaking change

**Comment by pedrorijo91** [comment]
released on https://github.com/feedzai/feedzai-openml-r/releases/tag/0.2.0
